import { useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { projectData } from './data/projectData'
import './App.css'

const navItems = [
  ['Dashboard', '/dashboard'], ['ML Comparison', '/ml-comparison'], ['History', '/history'],
  ['Hardware', '/hardware'], ['About', '/about'],
]

function DemoBadge() { return <span className="demo-badge" role="status"><i /> DEMO MODE</span> }
function StatusBadge({ children = 'Simulated' }) { return <span className="status-badge" role="status"><i />{children}</span> }
function SectionHeader({ eyebrow, title, copy }) { return <div className="section-header"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
function GlassCard({ children, className = '' }) { return <article className={`glass-card ${className}`}>{children}</article> }

function Navbar() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  return <><a className="skip-link" href="#main-content">Skip to main content</a><header className="navbar"><Link className="brand" to="/" onClick={() => setOpen(false)}><span className="brand-mark">SC</span><span>SmartClass<span> / IoT Lab</span></span></Link><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="primary-navigation" aria-label="Toggle navigation">{open ? '×' : '☰'}</button><nav id="primary-navigation" className={open ? 'nav-links open' : 'nav-links'} aria-label="Primary navigation">{navItems.map(([label, path]) => <NavLink key={path} to={path} className={location.pathname === path ? 'active' : ''} onClick={() => setOpen(false)}>{label}</NavLink>)}</nav></header></>
}

function Footer() { return <footer><span>SMARTCLASS / IOT LAB</span><span>Frontend demonstration environment · No live hardware connection</span></footer> }
function Page({ children, className = '' }) { return <><Navbar /><main id="main-content" className={`page ${className}`}>{children}</main><Footer /></> }

function ChartCard({ compact = false }) { return <GlassCard className={`chart-card ${compact ? 'compact' : ''}`}><div className="card-heading"><div><span className="eyebrow">SIMULATED TELEMETRY</span><h3>Demo Occupancy History</h3></div><StatusBadge /></div><div className="chart-wrap" role="img" aria-label="Demo occupancy history area chart showing simulated occupancy observations over time"><ResponsiveContainer width="100%" height={compact ? 220 : 280}><AreaChart data={projectData.history} margin={{ top: 10, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="occupancyFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff65a3" stopOpacity={0.34} /><stop offset="100%" stopColor="#ff65a3" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)" vertical={false} /><XAxis dataKey="time" stroke="#7e8299" tickLine={false} axisLine={false} /><YAxis stroke="#7e8299" tickLine={false} axisLine={false} /><Tooltip contentStyle={{ background: '#17182b', border: '1px solid rgba(255,255,255,.15)', borderRadius: 10, color: '#fff' }} /><Area type="monotone" dataKey="occupancy" stroke="#ff65a3" strokeWidth={3} fill="url(#occupancyFill)" /></AreaChart></ResponsiveContainer></div></GlassCard> }

function Home() { return <Page className="home-page"><section className="hero-grid"><div className="hero-copy"><DemoBadge /><h1>Smart Classroom<br /><em>Occupancy Detection</em></h1><p>A low-cost IoT and Machine Learning based system for monitoring and analyzing classroom occupancy.</p><div className="hero-actions"><Link className="button primary" to="/dashboard">View Dashboard <span>↗</span></Link><Link className="button ghost" to="/about">Explore Project <span>→</span></Link></div><div className="hero-note"><span className="pulse-dot" /> Arduino Uno + Machine Learning <span className="divider" /> Frontend prototype</div></div><SystemFlow /></section><section className="feature-section"><SectionHeader eyebrow="01 / CAPABILITIES" title="Built for clarity, designed to scale." copy="A focused interface for understanding the journey from sensing to insight." /><div className="feature-grid"><Feature icon="01" title="IoT Hardware" copy="Arduino Uno based classroom sensing and data collection." /><Feature icon="02" title="Machine Learning" copy="Lightweight machine learning techniques analyze occupancy-related data." /><Feature icon="03" title="Smart Monitoring" copy="An easy-to-understand dashboard presents occupancy information and system observations." /></div></section><section className="workflow-band"><SectionHeader eyebrow="02 / SYSTEM FLOW" title="From signal to story." /><div className="workflow">{['Classroom', 'Sensors', 'Arduino Uno', 'Sensor Data', 'Machine Learning', 'Occupancy Prediction', 'Dashboard'].map((item, index) => <div className="workflow-step" key={item}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong>{index < 6 && <b>→</b>}</div>)}</div></section></Page> }
function Feature({ icon, title, copy }) { return <GlassCard className="feature-card"><span className="feature-number">{icon}</span><h3>{title}</h3><p>{copy}</p><span className="card-arrow">↗</span></GlassCard> }
function SystemFlow() { return <div className="system-visual"><div className="visual-top"><span>LIVE SYSTEM MAP</span><span className="visual-status"><i /> ONLINE / DEMO</span></div><div className="flow-stack"><FlowNode label="Sensors" detail="Classroom inputs" icon="⌁" /><div className="flow-line" /><FlowNode label="Arduino Uno" detail="Data collection" icon="▣" highlight /><div className="flow-line" /><FlowNode label="Machine Learning" detail="Pattern analysis" icon="◌" /><div className="flow-line" /><FlowNode label="Occupancy Detection" detail="Dashboard insight" icon="◈" highlight /></div></div> }
function FlowNode({ label, detail, icon, highlight }) { return <div className={`flow-node ${highlight ? 'highlight' : ''}`}><span className="node-icon">{icon}</span><span><strong>{label}</strong><small>{detail}</small></span><span className="node-check">✓</span></div> }

function PageTitle({ eyebrow, title, copy, badge = true }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{badge && <DemoBadge />}</div> }
function Dashboard() { return <Page><PageTitle eyebrow="CONTROL ROOM / 01" title="Smart Classroom Dashboard" copy="Monitor classroom occupancy and system information." /><div className="dashboard-grid"><GlassCard className="occupancy-card"><div className="card-heading"><span className="eyebrow">CURRENT OCCUPANCY</span><StatusBadge>Simulated Data</StatusBadge></div><div className="occupancy-main"><div className="occupancy-ring"><strong>{projectData.occupancy.count}</strong><span>people</span></div><div><span className="occupancy-label">STATUS</span><h2>{projectData.occupancy.status}</h2><p>Estimated occupancy</p></div></div><div className="meter"><span style={{ width: '58%' }} /></div><div className="meter-meta"><span>Room utilization</span><span>58% <small>demo scale</small></span></div></GlassCard><div className="metrics-grid"><MetricCard label="Occupancy Status" value="Occupied" accent="pink" /><MetricCard label="Arduino Status" value="Demo / Simulated" /><MetricCard label="ML Prediction" value="Occupied" accent="violet" /><MetricCard label="Last Updated" value="Just now" /></div></div><div className="dashboard-lower"><ChartCard /><GlassCard className="prediction-card"><div className="card-heading"><div><span className="eyebrow">INFERENCE OUTPUT</span><h3>ML Prediction</h3></div><span className="prediction-icon">◈</span></div><div className="prediction-result"><span>Current result</span><strong>Occupied</strong></div><div className="prediction-details"><div><span>Model</span><strong>Demo Model</strong></div><div><span>Confidence</span><strong>Not Available</strong></div></div><p className="muted-note">Experimental model values are not connected in this frontend demo.</p></GlassCard></div><GlassCard className="sensor-card"><div className="card-heading"><div><span className="eyebrow">EXTENSIBLE INPUTS</span><h3>Sensor Readings</h3></div><span className="muted">3 slots available</span></div><div className="sensor-grid">{[1, 2, 3].map((item) => <div className="sensor-slot" key={item}><span className="sensor-placeholder">⌁</span><div><strong>Sensor Reading</strong><span>Demo Value · Simulated</span></div><b>--</b></div>)}</div></GlassCard></Page> }
function MetricCard({ label, value, accent = '' }) { return <GlassCard className="metric-card"><span className={`metric-icon ${accent}`}>◉</span><span className="metric-label">{label}</span><strong>{value}</strong><small>Demo data</small></GlassCard> }

function History() { return <Page><PageTitle eyebrow="OBSERVATIONS / 03" title="Occupancy History" copy="A readable timeline of simulated classroom observations." /><div className="history-layout"><ChartCard compact /><GlassCard className="observation-card"><div className="card-heading"><div><span className="eyebrow">RECENT OBSERVATIONS</span><h3>Activity log</h3></div><StatusBadge /></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Occupancy</th><th>Status</th></tr></thead><tbody>{projectData.history.slice(0, 4).map((row) => <tr key={row.time}><td>{row.time}</td><td><strong>{row.occupancy}</strong> people</td><td><StatusBadge>Demo</StatusBadge></td></tr>)}</tbody></table></div></GlassCard></div></Page> }
function MLComparison() { return <Page><PageTitle eyebrow="RESEARCH LENS / 02" title="Machine Learning Comparison" copy="Comparison of lightweight machine learning approaches for classroom occupancy detection." /><GlassCard className="comparison-card"><div className="comparison-intro"><div><span className="eyebrow">MODEL BENCHMARKS</span><h3>Research values, ready to connect</h3></div><span className="large-placeholder">%</span></div><div className="table-wrap"><table><thead><tr><th>Model</th><th>Accuracy</th><th>Precision</th><th>Recall</th><th>F1 Score</th></tr></thead><tbody>{['Model A', 'Model B', 'Model C'].map((model) => <tr key={model}><td><strong>{model}</strong><small>Awaiting project results</small></td><td>Not Available</td><td>Not Available</td><td>Not Available</td><td>Not Available</td></tr>)}</tbody></table></div><div className="callout"><span>i</span><p>Actual experimental values can be connected here later. This interface intentionally avoids fabricating research results.</p></div></GlassCard></Page> }
function Hardware() { return <Page><PageTitle eyebrow="ARCHITECTURE / 04" title="Hardware & System" copy="A conceptual view of the classroom sensing architecture." /><div className="hardware-grid"><GlassCard className="hardware-hero"><span className="hardware-icon">▣</span><span className="eyebrow">PRIMARY DEVICE</span><h2>Arduino Uno</h2><p>Conceptual role: collecting classroom sensor information before it moves through data processing and machine learning.</p><StatusBadge>Hardware Connection · Demo Mode</StatusBadge></GlassCard><GlassCard className="architecture-card"><div className="card-heading"><div><span className="eyebrow">SYSTEM ARCHITECTURE</span><h3>Signal pathway</h3></div><span className="muted">Conceptual</span></div><div className="architecture-flow">{['Sensors', 'Arduino Uno', 'Data Processing', 'Machine Learning', 'Occupancy Result', 'Web Dashboard'].map((step, index) => <div className="architecture-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < 5 && <b>↓</b>}</div>)}</div></GlassCard></div></Page> }
function About() { return <Page><PageTitle eyebrow="THE PROJECT / 05" title="Built for a smarter classroom." copy="A low-cost academic exploration of sensing, modeling, and useful visualization." badge={false} /><div className="about-grid"><GlassCard className="about-main"><span className="eyebrow">FULL PROJECT TITLE</span><h2>Low-Cost Smart Classroom Occupancy Detection Using Arduino Uno and Machine Learning: A Comparative Study of Lightweight Machine Learning Algorithms</h2><div className="about-copy"><div><span className="eyebrow">OBJECTIVE</span><p>The project explores a low-cost classroom occupancy detection system using Arduino-based sensing and lightweight machine learning techniques.</p></div><div><span className="eyebrow">SCOPE</span><p>Classroom occupancy detection, IoT sensing, machine learning, model comparison, and data visualization.</p></div></div></GlassCard><GlassCard className="tech-card"><span className="eyebrow">STACK / 06</span><h3>Technologies</h3><div className="tech-list">{['Arduino Uno', 'Machine Learning', 'React', 'JavaScript', 'CSS', 'Vite'].map((tech, index) => <span key={tech}><b>{String(index + 1).padStart(2, '0')}</b>{tech}</span>)}</div></GlassCard></div></Page> }

function App() { return <BrowserRouter><RouteMetadata /><Routes><Route path="/" element={<Home />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/ml-comparison" element={<MLComparison />} /><Route path="/history" element={<History />} /><Route path="/hardware" element={<Hardware />} /><Route path="/about" element={<About />} /><Route path="*" element={<Home />} /></Routes></BrowserRouter> }

function RouteMetadata() {
  const location = useLocation()
  useEffect(() => {
    const titles = { '/': 'Smart Classroom Occupancy Detection', '/dashboard': 'Dashboard | SmartClass', '/ml-comparison': 'ML Comparison | SmartClass', '/history': 'History | SmartClass', '/hardware': 'Hardware | SmartClass', '/about': 'About | SmartClass' }
    document.title = titles[location.pathname] || titles['/']
  }, [location.pathname])
  return null
}

export default App
